### ISSUE TITLE
[Feature] Adding nullable types

### ISSUE THREAD

**Issue by santigarcor** [std-library/type-guard#11]
Nuno, I've had cases where I need nullable strings, ints, etc. Do you see it useful as a new feature? Before I start working on it.

I imagine the api like this:
```php
type($variable)->asNullable()->string();
type($variable)->asNullable()->int();
```
or

```php
type($variable)->asNullableString();
type($variable)->asNullableInt();
```

I prefer the first one if I get to choose.

**Comment by nunomaduro** [comment]
Going to hold on this one for now.

**Comment by devnix** [comment]
@santigarcor you can check out https://github.com/azjezz/psl, which has your back covered 🦾

```php
nullable(string())->coerce($variable);
nullable(int())->coerce($variable);
```

You can mix and match the types to do any combination you need

**Comment by santigarcor** [comment]
@devnix thanks, I'll check that out when i get to my computer
