### ISSUE TITLE
Consider using Typhoon type system

### ISSUE THREAD

**Issue by vudaltsov** [std-library/type-guard#18]
Hi! I am an author of the [Typhoon](https://github.com/typhoon-php/typhoon) project. It's an ultimate reflection and type system for PHP with full support for generic resolution and many other things.

The cool thing about Typhoon is that it has a separate component for types that does not have any dependencies, see https://github.com/typhoon-php/type.

What if your project uses Typhoon Type system internally, so that one could write:

```php
use Typhoon\Type\types;

function config(): mixed {}

$apiKey = type(config('api_key'))->as(types::nonEmptyString);

// or
type(config('db'))->as(types::arrayShape([
    'user' => types::nonEmptyString,
    'pass' => types::nonEmptyString,
    'port' => types::positiveInt,
]));
```

I will be happy to help you and discuss how this could be done!

**Comment by nunomaduro** [comment]
No plans for that. Thanks tho!
